In [1]:
# from scipy import stats

In [1]:
import pandas as pd
#Tipo um excel mais fodão

In [2]:
import numpy as np
#Pra mexer com matriz e funções matemáticas mais complexas

In [4]:
# import matplotlib.pyplot as plt
# %matplotlib inline
# import seaborn as sns
##Para plotar os gráficos

In [3]:
import json
#Para ler arquivos json do firebrowse

In [4]:
import requests
#Para acessar o site do firbrowse

In [5]:
import csv
import math
##Até aqui foi só importação dos pacotes usados

In [30]:
#Pega o arquivo de gens e transofrma em list
arq = 'REACTOME_METABOLISM_OF_LIPIDS.v7.5.1.txt'
gensList=[]
with open(arq) as arq_gens:
    leitor = csv.reader(arq_gens, delimiter=',')
    for linha in leitor:
        gensList.extend(linha)
#gensList[0] = gensList[0][3:]
print(gensList)

['ACAA1', 'ACOT1', 'ACOT2', 'ACOT4', 'ACOT7', 'ACOX1', 'ACOX3', 'BAAT', 'ELOVL2', 'ELOVL5', 'ELOVL6', 'FADS1', 'FADS2', 'HACD1', 'HACD2', 'HADHA', 'HSD17B12', 'PECR', 'SCD', 'SCD5', 'TECR', 'YOD1', 'MGMT']

In [31]:
#Busca os dados no banco de dados firebrowse e cria um dataframe
dfLista = []
errGens = []
gensAux = []
testeTamanho = []
i=0
for g in gensList:
    link=''
    link+= 'http://firebrowse.org/api/v1/Samples/mRNASeq?format=json&gene='
    link+= g
    link+= '&cohort=GBM%2CGBMLGG%2CLGG&sample_type=NT%2CTM%2CTP%2CTR&protocol=RSEM&page=1&page_size=2000&sort_by=cohort'
    #verificar as p'aginas
    try:
        json_data = requests.get(link).json()
        if len(json_data['mRNASeq'])>2000:
            print(g + ': Tem mais de uma página')
#         testeTamanho.append(len(json_data['mRNASeq']))
        dfLista.append(pd.DataFrame(json_data['mRNASeq']))
#         print(len(dfLista[-1]))
#         dfLista[i].insert(loc=0, column='genes', value=[g,g,g])
        #Caso apareça Nan nos genes, há algum gen dando erro. Só se consegue ver deixando a parte de insert como comentário
        gensAux.append(g)
    except:
        errGens.append(g)
        
    i+=1
if errGens:
    print('Erro ao importar gens!!!')
df = pd.concat(dfLista, axis=0)
df.reset_index(drop=True)

Erro ao importar gens!!!

,cohort,expression_log2,gene,geneID,protocol,sample_type,tcga_participant_barcode,z-score
0,GBM,10.778518,ACAA1,30,RSEM,TP,TCGA-76-4925,0.305716
1,GBM,10.006744,ACAA1,30,RSEM,TP,TCGA-41-5651,-1.327331
2,GBM,11.158060,ACAA1,30,RSEM,TP,TCGA-41-2572,1.491877
3,GBM,10.559792,ACAA1,30,RSEM,TP,TCGA-32-2638,-0.248783
4,GBM,10.089807,ACAA1,30,RSEM,TP,TCGA-32-2634,-1.190511
5,GBM,11.078110,ACAA1,30,RSEM,TP,TCGA-32-2616,1.215441
6,GBM,10.495484,ACAA1,30,RSEM,TP,TCGA-32-2615,-0.396450
7,GBM,10.705150,ACAA1,30,RSEM,TP,TCGA-32-1970,0.110275
8,GBM,11.211284,ACAA1,30,RSEM,TP,TCGA-28-5216,1.684588
9,GBM,10.529794,ACAA1,30,RSEM,TP,TCGA-28-5215,-0.318484
10,GBM,11.135272,ACAA1,30,RSEM,TP,TCGA-28-5213,1.411520
11,GBM,10.059054,ACAA1,30,RSEM,TP,TCGA-28-5209,-1.242087
12,GBM,10.270474,ACAA1,30,RSEM,TP,TCGA-28-5208,-0.864269
13,GBM,10.635585,ACAA1,30,RSEM,TP,TCGA-28-5204,-0.066078
14,GBM,10.465067,ACAA1,30,RSEM,TP,TCGA-28-2514,-0.464035
15,GBM,10.943183,ACAA1,30,RSEM,TP,TCGA-28-2510,0.782287
16,GBM,11.080407,ACAA1,30,RSEM,TP,TCGA-28-1747,1.223171
17,GBM,10.626326,ACAA1,30,RSEM,TP,TCGA-27-2528,-0.088916
18,GBM,10.936325,ACAA1,30,RSEM,TP,TCGA-27-2524,0.761334
19,GBM,11.076715,ACAA1,30,RSEM,TP,TCGA-27-2519,1.210750
20,GBM,10.765469,ACAA1,30,RSEM,TP,TCGA-27-1834,0.270224
21,GBM,10.810877,ACAA1,30,RSEM,TP,TCGA-26-5136,0.395125
22,GBM,10.664256,ACAA1,30,RSEM,TP,TCGA-26-5135,0.005577
23,GBM,10.506722,ACAA1,30,RSEM,TP,TCGA-26-5134,-0.371117
24,GBM,10.608323,ACAA1,30,RSEM,TP,TCGA-26-5133,-0.132904
25,GBM,10.792084,ACAA1,30,RSEM,TP,TCGA-19-4065,0.342956
26,GBM,10.063968,ACAA1,30,RSEM,TP,TCGA-19-2625,-1.233919
27,GBM,10.224463,ACAA1,30,RSEM,TP,TCGA-19-1787,-0.951271
28,GBM,10.957961,ACAA1,30,RSEM,TP,TCGA-15-1444,0.827778
29,GBM,10.541097,ACAA1,30,RSEM,TP,TCGA-15-0742,-0.292393
...,...,...,...,...,...,...,...,...
29412,LGG,6.044267,MGMT,4255,RSEM,TP,TCGA-DB-A75K,-0.410166
29413,LGG,4.099960,MGMT,4255,RSEM,TP,TCGA-DB-A64X,-0.877605
29414,LGG,5.623208,MGMT,4255,RSEM,TP,TCGA-DB-A64W,-0.570023
29415,LGG,7.592029,MGMT,4255,RSEM,TP,TCGA-DB-A64V,0.804679
29416,LGG,6.324969,MGMT,4255,RSEM,TP,TCGA-DB-A64U,-0.274521
29417,LGG,7.507062,MGMT,4255,RSEM,TP,TCGA-DB-A64S,0.699078
29418,LGG,4.509145,MGMT,4255,RSEM,TP,TCGA-DB-A64R,-0.823791
29419,LGG,3.714564,MGMT,4255,RSEM,TP,TCGA-DB-A64Q,-0.916075
29420,LGG,5.673760,MGMT,4255,RSEM,TP,TCGA-DB-A64L,-0.553202
29421,LGG,6.473534,MGMT,4255,RSEM,TP,TCGA-DB-A4XH,-0.191307
29422,LGG,4.637077,MGMT,4255,RSEM,TP,TCGA-DB-A4XG,-0.803585
29423,LGG,6.166045,MGMT,4255,RSEM,TP,TCGA-DB-A4XE,-0.354543
29424,LGG,5.220520,MGMT,4255,RSEM,TP,TCGA-DB-A4XD,-0.684902
29425,LGG,5.533560,MGMT,4255,RSEM,TP,TCGA-DB-5280,-0.598441
29426,LGG,6.864247,MGMT,4255,RSEM,TP,TCGA-DB-5276,0.073201
29427,LGG,5.156146,MGMT,4255,RSEM,TP,TCGA-DB-5275,-0.700473
29428,LGG,8.264308,MGMT,4255,RSEM,TP,TCGA-DB-5274,1.900671
29429,LGG,7.362167,MGMT,4255,RSEM,TP,TCGA-DB-5273,0.532738
29430,LGG,6.705010,MGMT,4255,RSEM,TP,TCGA-DB-5270,-0.043308
29431,LGG,6.984636,MGMT,4255,RSEM,TP,TCGA-CS-6670,0.170229
29432,LGG,7.575271,MGMT,4255,RSEM,TP,TCGA-CS-6669,0.783357
29433,LGG,4.280147,MGMT,4255,RSEM,TP,TCGA-CS-6668,-0.855775
29434,LGG,7.056282,MGMT,4255,RSEM,TP,TCGA-CS-6188,0.231935
29435,LGG,6.911350,MGMT,4255,RSEM,TP,TCGA-CS-6186,0.110203
29436,LGG,7.188176,MGMT,4255,RSEM,TP,TCGA-CS-5397,0.353862
29437,LGG,4.153222,MGMT,4255,RSEM,TP,TCGA-CS-5396,-0.871433
29438,LGG,5.675765,MGMT,4255,RSEM,TP,TCGA-CS-5390,-0.552523
29439,LGG,7.740418,MGMT,4255,RSEM,TP,TCGA-CS-4944,1.004700
29440,LGG,6.702550,MGMT,4255,RSEM,TP,TCGA-CS-4942,-0.045009
29441,LGG,6.921845,MGMT,4255,RSEM,TP,TCGA-CS-4938,0.118612

In [32]:
df.to_csv('KEGG_BIOSYNTHESIS_OF_UNSATURATED_FATTY_ACIDS.csv')

In [16]:
dfLista

[     cohort  expression_log2   gene  geneID protocol sample_type  \
 0       GBM         9.260115  ABHD5   51099     RSEM          TP
 1       GBM        10.254215  ABHD5   51099     RSEM          TP
 2       GBM        10.240263  ABHD5   51099     RSEM          TP
 3       GBM        10.350961  ABHD5   51099     RSEM          TP
 4       GBM         9.932945  ABHD5   51099     RSEM          TP
 5       GBM        10.080868  ABHD5   51099     RSEM          TR
 6       GBM         9.480741  ABHD5   51099     RSEM          TR
 7       GBM         9.879899  ABHD5   51099     RSEM          TP
 8       GBM        10.079199  ABHD5   51099     RSEM          TP
 9       GBM         9.891006  ABHD5   51099     RSEM          TP
 10      GBM        10.097227  ABHD5   51099     RSEM          TP
 11      GBM         9.707349  ABHD5   51099     RSEM          TP
 12      GBM         9.626225  ABHD5   51099     RSEM          TP
 13      GBM         9.949427  ABHD5   51099     RSEM          TR
 14      GBM         9.551158  ABHD5   51099     RSEM          TP
 15      GBM         9.810992  ABHD5   51099     RSEM          TP
 16      GBM         8.728670  ABHD5   51099     RSEM          TP
 17      GBM        10.017689  ABHD5   51099     RSEM          TP
 18      GBM         9.691839  ABHD5   51099     RSEM          TP
 19      GBM         8.777453  ABHD5   51099     RSEM          TP
 20      GBM        10.003675  ABHD5   51099     RSEM          TP
 21      GBM        10.334700  ABHD5   51099     RSEM          TP
 22      GBM         9.192864  ABHD5   51099     RSEM          TP
 23      GBM         9.461796  ABHD5   51099     RSEM          TP
 24      GBM         9.570333  ABHD5   51099     RSEM          TP
 25      GBM         9.086716  ABHD5   51099     RSEM          NT
 26      GBM         9.419989  ABHD5   51099     RSEM          TP
 27      GBM        10.071619  ABHD5   51099     RSEM          TP
 28      GBM         9.754902  ABHD5   51099     RSEM          TP
 29      GBM         9.671367  ABHD5   51099     RSEM          TP
 ...     ...              ...    ...     ...      ...         ...
 1372    LGG         9.721655  ABHD5   51099     RSEM          TP
 1373    LGG         9.830683  ABHD5   51099     RSEM          TP
 1374    LGG         9.313443  ABHD5   51099     RSEM          TP
 1375    LGG         9.860665  ABHD5   51099     RSEM          TP
 1376    LGG         9.220863  ABHD5   51099     RSEM          TP
 1377    LGG         9.685924  ABHD5   51099     RSEM          TP
 1378    LGG         9.187816  ABHD5   51099     RSEM          TP
 1379    LGG         9.641782  ABHD5   51099     RSEM          TP
 1380    LGG         9.894707  ABHD5   51099     RSEM          TP
 1381    LGG         9.259800  ABHD5   51099     RSEM          TP
 1382    LGG         9.993705  ABHD5   51099     RSEM          TP
 1383    LGG         7.975601  ABHD5   51099     RSEM          TP
 1384    LGG        10.020428  ABHD5   51099     RSEM          TP
 1385    LGG         9.361391  ABHD5   51099     RSEM          TP
 1386    LGG         9.591295  ABHD5   51099     RSEM          TP
 1387    LGG         9.423459  ABHD5   51099     RSEM          TP
 1388    LGG         9.367198  ABHD5   51099     RSEM          TP
 1389    LGG         9.758530  ABHD5   51099     RSEM          TP
 1390    LGG         9.465307  ABHD5   51099     RSEM          TP
 1391    LGG         9.372801  ABHD5   51099     RSEM          TP
 1392    LGG         9.455110  ABHD5   51099     RSEM          TP
 1393    LGG        10.497335  ABHD5   51099     RSEM          TP
 1394    LGG        10.469505  ABHD5   51099     RSEM          TP
 1395    LGG         9.366490  ABHD5   51099     RSEM          TP
 1396    LGG         9.706984  ABHD5   51099     RSEM          TP
 1397    LGG         9.497320  ABHD5   51099     RSEM          TP
 1398    LGG         9.515773  ABHD5   51099     RSEM          TP
 1399    LGG         9.645104  ABHD5   51099     RSEM          TP
 1400    LGG         9.499054  ABHD5   51099     RSEM          TP
 1401    LGG         9.661304  ABHD5   51099     RSEM          TP

      tcga_participant_barcode   z-score
 0                TCGA-15-0742 -0.784229
 1                TCGA-14-2554  1.634480
 2                TCGA-14-1829  1.587730
 3                TCGA-14-1825  1.971378
 4                TCGA-14-1823  0.664787
 5                TCGA-14-1402  1.084546
 6                TCGA-14-1034 -0.381275
 7                TCGA-14-1034  0.524440
 8                TCGA-14-0817  1.079568
 9                TCGA-14-0790  0.553402
 10               TCGA-14-0789  1.133667
 11               TCGA-14-0787  0.102021
 12               TCGA-14-0781 -0.079780
 13               TCGA-14-0736  0.709456
 14               TCGA-12-5299 -0.239139
 15               TCGA-12-5295  0.349666
 16               TCGA-12-3653 -1.535659
 17               TCGA-12-3652  0.899986
 18               TCGA-12-3650  0.066468
 19               TCGA-12-1597 -1.477634
 20               TCGA-12-0821  0.860132
 21               TCGA-12-0619  1.913159
 22               TCGA-12-0618 -0.895295
 23               TCGA-12-0616 -0.418346
 24               TCGA-08-0386 -0.199219
 25               TCGA-06-AABW -1.060398
 26               TCGA-06-5859 -0.498448
 27               TCGA-06-5858  1.057021
 28               TCGA-06-5856  0.213439
 29               TCGA-06-5418  0.020122
 ...                       ...       ...
 1372             TCGA-DB-5281  0.479085
 1373             TCGA-DB-5280  0.790986
 1374             TCGA-DB-5279 -0.500074
 1375             TCGA-DB-5278  0.880969
 1376             TCGA-DB-5277 -0.686168
 1377             TCGA-DB-5276  0.381892
 1378             TCGA-DB-5275 -0.749757
 1379             TCGA-DB-5274  0.265095
 1380             TCGA-DB-5273  0.985431
 1381             TCGA-DB-5270 -0.609353
 1382             TCGA-CS-6670  1.303606
 1383             TCGA-CS-6669 -2.309614
 1384             TCGA-CS-6668  1.393302
 1385             TCGA-CS-6667 -0.398896
 1386             TCGA-CS-6666  0.135818
 1387             TCGA-CS-6665 -0.262828
 1388             TCGA-CS-6290 -0.386411
 1389             TCGA-CS-6188  0.581949
 1390             TCGA-CS-6186 -0.167726
 1391             TCGA-CS-5397 -0.374320
 1392             TCGA-CS-5396 -0.191155
 1393             TCGA-CS-5395  3.307964
 1394             TCGA-CS-5394  3.178010
 1395             TCGA-CS-5393 -0.387937
 1396             TCGA-CS-5390  0.438887
 1397             TCGA-CS-4944 -0.093091
 1398             TCGA-CS-4943 -0.049312
 1399             TCGA-CS-4942  0.273760
 1400             TCGA-CS-4941 -0.089002
 1401             TCGA-CS-4938  0.316307

 [1402 rows x 8 columns],
      cohort  expression_log2   gene  geneID protocol sample_type  \
 0       GBM        10.406961  ACACA      31     RSEM          TP
 1       GBM        10.819052  ACACA      31     RSEM          TP
 2       GBM        11.184720  ACACA      31     RSEM          TP
 3       GBM        10.276288  ACACA      31     RSEM          TP
 4       GBM        10.221073  ACACA      31     RSEM          TP
 5       GBM        10.860488  ACACA      31     RSEM          TP
 6       GBM        11.010235  ACACA      31     RSEM          TP
 7       GBM        11.428071  ACACA      31     RSEM          TP
 8       GBM        10.115017  ACACA      31     RSEM          TP
 9       GBM        10.319669  ACACA      31     RSEM          TP
 10      GBM        10.318666  ACACA      31     RSEM          TP
 11      GBM        10.968038  ACACA      31     RSEM          TP
 12      GBM         9.601348  ACACA      31     RSEM          TP
 13      GBM        10.199947  ACACA      31     RSEM          TP
 14      GBM        10.135205  ACACA      31     RSEM          TP
 15      GBM        11.179753  ACACA      31     RSEM          TP
 16      GBM        10.088389  ACACA      31     RSEM          TP
 17      GBM        11.238950  ACACA      31     RSEM          TP
 18      GBM        10.434196  ACACA      31     RSEM          TP
 19      GBM         9.508484  ACACA      31     RSEM          TP
 20      GBM        10.372112  ACACA      31     RSEM          TP
 21      GBM        11.253395  ACACA      31     RSEM          TP
 22      GBM        10.568509  ACACA      31     RSEM          TP
 23      GBM        10.813187  ACACA      31     RSEM          TP
 24      GBM        10.689418  ACACA      31     RSEM          TP
 25      GBM        11.617875  ACACA      31     RSEM          TP
 26      GBM         9.097200  ACACA      31     RSEM          TP
 27      GBM        10.885889  ACACA      31     RSEM          TP
 28      GBM        10.409045  ACACA      31     RSEM          TP
 29      GBM        10.274131  ACACA      31     RSEM          TP
 ...     ...              ...    ...     ...      ...         ...
 1372    LGG        11.762983  ACACA      31     RSEM          TP
 1373    LGG        10.662270  ACACA      31     RSEM          TP
 1374    LGG        10.880378  ACACA      31     RSEM          TP
 1375    LGG        12.418134  ACACA      31     RSEM          TP
 1376    LGG        11.619753  ACACA      31     RSEM          TP
 1377    LGG        11.353800  ACACA      31     RSEM          TP
 1378    LGG        11.165770  ACACA      31     RSEM          TP
 1379    LGG        11.250781  ACACA      31     RSEM          TP
 1380    LGG        11.644363  ACACA      31     RSEM          TP
 1381    LGG        11.885978  ACACA      31     RSEM          TP
 1382    LGG        11.182155  ACACA      31     RSEM          TP
 1383    LGG        11.797837  ACACA      31     RSEM          TP
 1384    LGG        11.376534  ACACA      31     RSEM          TP
 1385    LGG        11.450695  ACACA      31     RSEM          TP
 1386    LGG        11.838616  ACACA      31     RSEM          TP
 1387    LGG        11.351499  ACACA      31     RSEM          TP
 1388    LGG        11.582691  ACACA      31     RSEM          TP
 1389    LGG        11.652943  ACACA      31     RSEM          TP
 1390    LGG        11.703436  ACACA      31     RSEM          TP
 1391    LGG        11.446243  ACACA      31     RSEM          TP
 1392    LGG        11.018119  ACACA      31     RSEM          TP
 1393    LGG        10.939723  ACACA      31     RSEM          TP
 1394    LGG        10.817449  ACACA      31     RSEM          TP
 1395    LGG        10.896267  ACACA      31     RSEM          TP
 1396    LGG        11.303633  ACACA      31     RSEM          TP
 1397    LGG        11.560705  ACACA      31     RSEM          TP
 1398    LGG        12.273871  ACACA      31     RSEM          TP
 1399    LGG        11.619138  ACACA      31     RSEM          TP
 1400    LGG        11.608322  ACACA      31     RSEM          TP
 1401    LGG        11.621323  ACACA      31     RSEM          TP

      tcga_participant_barcode   z-score
 0                TCGA-76-4932 -0.300786
 1                TCGA-76-4931  0.430253
 2                TCGA-76-4929  1.279016
 3                TCGA-76-4928 -0.492262
 4                TCGA-76-4927 -0.568099
 5                TCGA-76-4926  0.515982
 6                TCGA-76-4925  0.847161
 7                TCGA-41-5651  1.975562
 8                TCGA-41-4097 -0.705871
 9                TCGA-41-3915 -0.430608
 10               TCGA-41-2572 -0.432055
 11               TCGA-41-2571  0.750335
 12               TCGA-32-5222 -1.246902
 13               TCGA-32-4213 -0.596356
 14               TCGA-32-2638 -0.680420
 15               TCGA-32-2634  1.265986
 16               TCGA-32-2632 -0.738900
 17               TCGA-32-2616  1.424226
 18               TCGA-32-2615 -0.258648
 19               TCGA-32-1982 -1.325765
 20               TCGA-32-1980 -0.353558
 21               TCGA-32-1970  1.463836
 22               TCGA-28-5220 -0.038793
 23               TCGA-28-5218  0.418317
 24               TCGA-28-5216  0.177411
 25               TCGA-28-5215  2.606548
 26               TCGA-28-5213 -1.619995
 27               TCGA-28-5209  0.569766
 28               TCGA-28-5208 -0.297589
 29               TCGA-28-5207 -0.495279
 ...                       ...       ...
 1372             TCGA-DU-5871  0.938455
 1373             TCGA-DU-5847 -1.116622
 1374             TCGA-DH-A7UT -0.823594
 1375             TCGA-DH-5144  3.151660
 1376             TCGA-DB-A64W  0.574539
 1377             TCGA-DB-A64U -0.012433
 1378             TCGA-DB-A64Q -0.366757
 1379             TCGA-DB-A64P -0.212267
 1380             TCGA-DB-A64L  0.634527
 1381             TCGA-DB-A4XH  1.281125
 1382             TCGA-DB-A4XD -0.337686
 1383             TCGA-DB-A4XB  1.032613
 1384             TCGA-DB-A4XA  0.033621
 1385             TCGA-DB-5281  0.189004
 1386             TCGA-DB-5278  1.145704
 1387             TCGA-DB-5275 -0.017054
 1388             TCGA-DB-5270  0.486112
 1389             TCGA-CS-6670  0.655681
 1390             TCGA-CS-6666  0.782760
 1391             TCGA-CS-6665  0.179448
 1392             TCGA-CS-6290 -0.614368
 1393             TCGA-CS-6188 -0.735893
 1394             TCGA-CS-6186 -0.912732
 1395             TCGA-CS-5397 -0.800464
 1396             TCGA-CS-5395 -0.111529
 1397             TCGA-CS-5393  0.434718
 1398             TCGA-CS-5390  2.574646
 1399             TCGA-CS-4943  0.573054
 1400             TCGA-CS-4942  0.547024
 1401             TCGA-CS-4938  0.578338

 [1402 rows x 8 columns],
      cohort  expression_log2  gene  geneID protocol sample_type  \
 0       GBM        12.902510  ACLY      47     RSEM          TP
 1       GBM        12.002115  ACLY      47     RSEM          TP
 2       GBM        11.688827  ACLY      47     RSEM          TP
 3       GBM        12.653659  ACLY      47     RSEM          TP
 4       GBM        12.095665  ACLY      47     RSEM          TP
 5       GBM        12.213903  ACLY      47     RSEM          TP
 6       GBM        12.130721  ACLY      47     RSEM          TP
 7       GBM        12.257536  ACLY      47     RSEM          TP
 8       GBM        12.294289  ACLY      47     RSEM          TP
 9       GBM        12.318745  ACLY      47     RSEM          TP
 10      GBM        12.109299  ACLY      47     RSEM          TP
 11      GBM        11.498840  ACLY      47     RSEM          TP
 12      GBM        11.613552  ACLY      47     RSEM          TP
 13      GBM        12.623572  ACLY      47     RSEM          TP
 14      GBM        11.706661  ACLY      47     RSEM          TP
 15      GBM        12.066294  ACLY      47     RSEM          TP
 16      GBM        12.245718  ACLY      47     RSEM          TP
 17      GBM        10.967326  ACLY      47     RSEM          TP
 18      GBM        12.580201  ACLY      47     RSEM          TP
 19      GBM        11.667275  ACLY      47     RSEM          TP
 20      GBM        11.897939  ACLY      47     RSEM          TR
 21      GBM        12.147640  ACLY      47     RSEM          TP
 22      GBM        11.330487  ACLY      47     RSEM          TP
 23      GBM        11.233231  ACLY      47     RSEM          TP
 24      GBM        12.629959  ACLY      47     RSEM          TR
 25      GBM        12.113364  ACLY      47     RSEM          TP
 26      GBM        12.299756  ACLY      47     RSEM          TP
 27      GBM        12.137050  ACLY      47     RSEM          TP
 28      GBM        11.587247  ACLY      47     RSEM          TP
 29      GBM        12.096760  ACLY      47     RSEM          TP
 ...     ...              ...   ...     ...      ...         ...
 1372    LGG        12.103224  ACLY      47     RSEM          TR
 1373    LGG        12.058558  ACLY      47     RSEM          TP
 1374    LGG        11.962601  ACLY      47     RSEM          TP
 1375    LGG        11.669394  ACLY      47     RSEM          TP
 1376    LGG        12.397843  ACLY      47     RSEM          TP
 1377    LGG        11.825154  ACLY      47     RSEM          TP
 1378    LGG        11.333485  ACLY      47     RSEM          TP
 1379    LGG        11.691165  ACLY      47     RSEM          TP
 1380    LGG        11.655367  ACLY      47     RSEM          TP
 1381    LGG        11.802330  ACLY      47     RSEM          TP
 1382    LGG        11.245272  ACLY      47     RSEM          TP
 1383    LGG        11.956897  ACLY      47     RSEM          TP
 1384    LGG        12.503984  ACLY      47     RSEM          TP
 1385    LGG        11.734569  ACLY      47     RSEM          TP
 1386    LGG        11.783021  ACLY      47     RSEM          TP
 1387    LGG        12.513190  ACLY      47     RSEM          TP
 1388    LGG        11.900791  ACLY      47     RSEM          TP
 1389    LGG        11.866820  ACLY      47     RSEM          TP
 1390    LGG        11.877291  ACLY      47     RSEM          TP
 1391    LGG        11.382381  ACLY      47     RSEM          TP
 1392    LGG        12.229228  ACLY      47     RSEM          TP
 1393    LGG        11.412178  ACLY      47     RSEM          TP
 1394    LGG        12.561545  ACLY      47     RSEM          TP
 1395    LGG        11.373307  ACLY      47     RSEM          TP
 1396    LGG        12.152737  ACLY      47     RSEM          TP
 1397    LGG        11.795132  ACLY      47     RSEM          TP
 1398    LGG        12.070534  ACLY      47     RSEM          TP
 1399    LGG        12.263048  ACLY      47     RSEM          TP
 1400    LGG        12.007362  ACLY      47     RSEM          TP
 1401    LGG        11.992323  ACLY      47     RSEM          TP

      tcga_participant_barcode   z-score
 0                TCGA-76-4932  2.823119
 1                TCGA-76-4927 -0.050665
 2                TCGA-76-4926 -0.697978
 3                TCGA-76-4925  1.842410
 4                TCGA-41-3915  0.171498
 5                TCGA-32-5222  0.473709
 6                TCGA-32-2634  0.258533
 7                TCGA-28-5204  0.591640
 8                TCGA-28-2514  0.693782
 9                TCGA-28-2509  0.763204
 10               TCGA-27-2528  0.205098
 11               TCGA-27-1832 -1.027287
 12               TCGA-27-1831 -0.833662
 13               TCGA-26-5139  1.734895
 14               TCGA-26-5136 -0.664780
 15               TCGA-26-5135  0.100190
 16               TCGA-26-5134  0.559346
 17               TCGA-19-4065 -1.748293
 18               TCGA-19-2619  1.583805
 19               TCGA-19-1787 -0.737551
 20               TCGA-19-0957 -0.281686
 21               TCGA-15-0742  0.301300
 22               TCGA-14-1829 -1.284978
 23               TCGA-14-1823 -1.420700
 24               TCGA-14-1034  1.757532
 25               TCGA-14-0781  0.215176
 26               TCGA-12-5299  0.709199
 27               TCGA-12-5295  0.274473
 28               TCGA-12-3653 -0.879434
 29               TCGA-12-3650  0.174187
 ...                       ...       ...
 1372             TCGA-DU-5870  0.476569
 1373             TCGA-DU-5870  0.366993
 1374             TCGA-DU-5855  0.142755
 1375             TCGA-DU-5853 -0.456896
 1376             TCGA-DU-5852  1.290900
 1377             TCGA-DU-5847 -0.153536
 1378             TCGA-DH-A7UT -1.009594
 1379             TCGA-DH-A66F -0.416438
 1380             TCGA-DB-A75M -0.482641
 1381             TCGA-DB-A64U -0.200063
 1382             TCGA-DB-A64L -1.134634
 1383             TCGA-DB-A4XE  0.129890
 1384             TCGA-DB-5281  1.627479
 1385             TCGA-DB-5280 -0.333934
 1386             TCGA-DB-5279 -0.238854
 1387             TCGA-DB-5278  1.657854
 1388             TCGA-DB-5277  0.006014
 1389             TCGA-DB-5276 -0.066680
 1390             TCGA-DB-5270 -0.044455
 1391             TCGA-CS-6669 -0.936920
 1392             TCGA-CS-6668  0.804611
 1393             TCGA-CS-6667 -0.891410
 1394             TCGA-CS-6665  1.820632
 1395             TCGA-CS-6290 -0.950594
 1396             TCGA-CS-5397  0.602066
 1397             TCGA-CS-5393 -0.214585
 1398             TCGA-CS-5390  0.396042
 1399             TCGA-CS-4943  0.897644
 1400             TCGA-CS-4942  0.245501
 1401             TCGA-CS-4938  0.210623

 [1402 rows x 8 columns],

In [20]:
errGens

['HILPDA']

In [13]:
df

,cohort,expression_log2,gene,geneID,protocol,sample_type,tcga_participant_barcode,z-score
0,GBM,9.25041,SPTLC2,9517,RSEM,TP,TCGA-02-2485,-0.472275
1,GBM,8.95677,SPTLC2,9517,RSEM,TP,TCGA-02-2483,-0.734865
2,GBM,10.1352,SPTLC2,9517,RSEM,TP,TCGA-02-0055,0.734721
3,GBM,10.0232,SPTLC2,9517,RSEM,TP,TCGA-02-0047,0.538062
4,GBM,9.1036,SPTLC2,9517,RSEM,TP,TCGA-76-4931,-0.610241
5,GBM,9.32037,SPTLC2,9517,RSEM,TP,TCGA-76-4929,-0.401431
6,GBM,9.88116,SPTLC2,9517,RSEM,TP,TCGA-76-4928,0.309644
7,GBM,10.1289,SPTLC2,9517,RSEM,TP,TCGA-76-4927,0.723206
8,GBM,9.76845,SPTLC2,9517,RSEM,TP,TCGA-41-5651,0.143724
9,GBM,10.2153,SPTLC2,9517,RSEM,TP,TCGA-41-4097,0.88502
10,GBM,9.9155,SPTLC2,9517,RSEM,TP,TCGA-41-3915,0.362817
11,GBM,8.87227,SPTLC2,9517,RSEM,TP,TCGA-41-2572,-0.801044
12,GBM,10.0711,SPTLC2,9517,RSEM,TP,TCGA-41-2571,0.620368
13,GBM,9.51674,SPTLC2,9517,RSEM,TP,TCGA-32-5222,-0.183183
14,GBM,9.46988,SPTLC2,9517,RSEM,TP,TCGA-32-2638,-0.237989
15,GBM,8.70724,SPTLC2,9517,RSEM,TP,TCGA-32-2616,-0.919634
16,GBM,9.2257,SPTLC2,9517,RSEM,TP,TCGA-32-2615,-0.496491
17,GBM,9.47682,SPTLC2,9517,RSEM,TP,TCGA-32-1970,-0.229988
18,GBM,9.22827,SPTLC2,9517,RSEM,TP,TCGA-28-5220,-0.493993
19,GBM,9.1856,SPTLC2,9517,RSEM,TP,TCGA-28-5216,-0.534916
20,GBM,10.2011,SPTLC2,9517,RSEM,TP,TCGA-28-5215,0.857833
21,GBM,9.44615,SPTLC2,9517,RSEM,TP,TCGA-28-5213,-0.26508
22,GBM,9.84627,SPTLC2,9517,RSEM,TP,TCGA-28-5208,0.256887
23,GBM,9.40228,SPTLC2,9517,RSEM,TP,TCGA-28-5207,-0.313989
24,GBM,9.66334,SPTLC2,9517,RSEM,TP,TCGA-28-2514,0.000250438
25,GBM,10.1852,SPTLC2,9517,RSEM,TP,TCGA-28-2513,0.827567
26,GBM,10.2841,SPTLC2,9517,RSEM,TP,TCGA-28-1747,1.02095
27,GBM,9.35519,SPTLC2,9517,RSEM,TP,TCGA-27-2528,-0.364865
28,GBM,8.93632,SPTLC2,9517,RSEM,TP,TCGA-27-2524,-0.751236
29,GBM,9.33587,SPTLC2,9517,RSEM,TP,TCGA-27-2523,-0.385261
...,...,...,...,...,...,...,...,...
1372,LGG,8.67086,GGT5,2687,RSEM,TP,TCGA-DU-5851,-0.514563
1373,LGG,8.87329,GGT5,2687,RSEM,TP,TCGA-DH-A66G,-0.425289
1374,LGG,9.11669,GGT5,2687,RSEM,TP,TCGA-DH-A66F,-0.299965
1375,LGG,8.98788,GGT5,2687,RSEM,TP,TCGA-DH-A66D,-0.368919
1376,LGG,10.2591,GGT5,2687,RSEM,TR,TCGA-DH-A669,0.674785
1377,LGG,9.12263,GGT5,2687,RSEM,TP,TCGA-DH-A669,-0.296636
1378,LGG,8.43399,GGT5,2687,RSEM,TP,TCGA-DH-5143,-0.6043
1379,LGG,9.34868,GGT5,2687,RSEM,TP,TCGA-DH-5140,-0.159144
1380,LGG,10.9675,GGT5,2687,RSEM,TP,TCGA-DB-A75P,1.80444
1381,LGG,9.91947,GGT5,2687,RSEM,TP,TCGA-DB-A64P,0.300991
1382,LGG,8.61987,GGT5,2687,RSEM,TP,TCGA-DB-A4XD,-0.535145
1383,LGG,7.11551,GGT5,2687,RSEM,TP,TCGA-DB-A4XB,-0.905563
1384,LGG,9.34656,GGT5,2687,RSEM,TP,TCGA-DB-A4XA,-0.160533
1385,LGG,9.89012,GGT5,2687,RSEM,TP,TCGA-DB-5281,0.272636
1386,LGG,8.49198,GGT5,2687,RSEM,TP,TCGA-DB-5280,-0.583672
1387,LGG,8.34884,GGT5,2687,RSEM,TP,TCGA-DB-5278,-0.633123
1388,LGG,11.3091,GGT5,2687,RSEM,TP,TCGA-DB-5274,2.58246
1389,LGG,8.79856,GGT5,2687,RSEM,TP,TCGA-DB-5270,-0.459712
1390,LGG,9.36035,GGT5,2687,RSEM,TP,TCGA-CS-6670,-0.151444
1391,LGG,10.9877,GGT5,2687,RSEM,TP,TCGA-CS-6667,1.84564
1392,LGG,10.2886,GGT5,2687,RSEM,TP,TCGA-CS-6666,0.711555
1393,LGG,9.15123,GGT5,2687,RSEM,TP,TCGA-CS-6290,-0.28041
1394,LGG,10.0656,GGT5,2687,RSEM,TP,TCGA-CS-6188,0.45106
1395,LGG,8.77203,GGT5,2687,RSEM,TP,TCGA-CS-5397,-0.471511
1396,LGG,9.50713,GGT5,2687,RSEM,TP,TCGA-CS-5396,-0.049085
1397,LGG,9.14144,GGT5,2687,RSEM,TP,TCGA-CS-5394,-0.286002
1398,LGG,9.40992,GGT5,2687,RSEM,TP,TCGA-CS-5393,-0.11803
1399,LGG,10.2256,GGT5,2687,RSEM,TP,TCGA-CS-4944,0.633871
1400,LGG,7.91601,GGT5,2687,RSEM,TP,TCGA-CS-4942,-0.756001
1401,LGG,9.25611,GGT5,2687,RSEM,TP,TCGA-CS-4941,-0.218066